import json
import logging
from typing import AsyncGenerator, TYPE_CHECKING
from sqlalchemy.ext.asyncio import AsyncSession
from uuid import UUID

from src.agent import AgentDeps
from src.agent.agent import agent, parse_agent_output
from src.core.config import settings
from src.repositories import generation_repo
from src.repositories import voice_profile_repo
from src.services.voice_profile import (
    get_voice_profile_prompt_fragment,
    validate_voice_profile_constraints
)
from src.services import byok
from src.services.generation import check_and_increment_usage

if TYPE_CHECKING:
    from src.models.client import Client
    from src.models.tenant import Tenant

logger = logging.getLogger(__name__)

async def generate_stream(deps: AgentDeps, brief: str, model_id: str, api_key: str | None) -> AsyncGenerator[str, None]:
    from typing import Any
    kwargs: dict[str, Any] = {}
    if model_id:
        if model_id == "test":
            from pydantic_ai.models.test import TestModel
            kwargs["model"] = TestModel(custom_output_text="<DRAFT>\nThis is a test draft generated by TestModel.\n</DRAFT>\n<SOURCES>\n[{\"type\": \"kb\", \"document_id\": \"123e4567-e89b-12d3-a456-426614174000\", \"excerpt\": \"test\"}]\n</SOURCES>")
        elif "gemini" in model_id.lower():
            from pydantic_ai.models.google import GoogleModel
            from pydantic_ai.providers.google import GoogleProvider
            active_api_key = api_key or settings.GEMINI_API_KEY
            kwargs["model"] = GoogleModel(model_id, provider=GoogleProvider(api_key=active_api_key)) if active_api_key else GoogleModel(model_id)
        elif "gpt" in model_id.lower() or "o1" in model_id.lower():
            from pydantic_ai.models.openai import OpenAIChatModel
            from pydantic_ai.providers.openai import OpenAIProvider
            kwargs["model"] = OpenAIChatModel(model_id, provider=OpenAIProvider(api_key=api_key)) if api_key else OpenAIChatModel(model_id)
        elif "claude" in model_id.lower():
            from pydantic_ai.models.anthropic import AnthropicModel
            from pydantic_ai.providers.anthropic import AnthropicProvider
            kwargs["model"] = AnthropicModel(model_id, provider=AnthropicProvider(api_key=api_key)) if api_key else AnthropicModel(model_id)
        else:
            kwargs["model"] = model_id

    accumulated_text = ""
    try:
        async with agent.run_stream(brief, deps=deps, **kwargs) as result:
            async for text in result.stream_text(delta=True):
                accumulated_text += text
                yield f"0:{json.dumps(text)}\n"
        
        # Stream completed successfully
        yield f'd:{json.dumps({"finishReason":"stop"})}\n'

        # Now parse the accumulated text to extract sources
        draft, sources = parse_agent_output(accumulated_text)
        yield f"8:{json.dumps(sources)}\n"

    except Exception as e:
        logger.exception("Streaming error")
        yield f"3:{json.dumps(str(e))}\n"
        raise

async def stream_generation_content(
    session: AsyncSession, client: "Client", tenant: "Tenant", brief: str, request_id: UUID
) -> AsyncGenerator[str, None]:
    
    model_id = None
    try:
        # Enforce usage cap
        await check_and_increment_usage(session, client)

        # Resolve model
        model_id, api_key = byok.resolve_model_for_client(client)

        # Load voice profile fragment
        vp_fragment = await get_voice_profile_prompt_fragment(session, client.id)
        
        # Build deps
        deps = AgentDeps(
            session=session,
            client_id=client.id,
            tenant_id=tenant.id,
            voice_profile_fragment=vp_fragment,
            tavily_api_key=settings.TAVILY_API_KEY or ""
        )
        
        # Generate stream
        accumulated_chunks = []
        try:
            async for chunk in generate_stream(deps, brief, model_id, api_key):
                accumulated_chunks.append(chunk)
                yield chunk
        except Exception as e:
            await generation_repo.update_generation_request(
                session=session,
                request_id=request_id,
                status="failed",
                error_message=str(e)
            )
            return

        full_text = ""
        sources_list = []
        for chunk in accumulated_chunks:
            if chunk.startswith("0:"):
                # chunk is 0:"some text"\n -> slice [2:] and strip
                full_text += json.loads(chunk[2:].strip())
            elif chunk.startswith("8:"):
                sources_list = json.loads(chunk[2:].strip())
        
        error_msg = None
        
        try:
            draft_text, _ = parse_agent_output(full_text)
            profile = await voice_profile_repo.get_voice_profile(session, client.id)
            if profile:
                violations = await validate_voice_profile_constraints(profile, draft_text)
                if violations:
                    error_msg = f"Voice profile constraint violations: used banned words/phrases: {', '.join(violations)}"
        except ValueError as ve:
            error_msg = f"Output parsing error: {ve}"
            draft_text = full_text

        # Update request
        await generation_repo.update_generation_request(
            session=session,
            request_id=request_id,
            output=draft_text,
            sources_used=sources_list,
            llm_model_used=model_id,
            llm_provider_used=client.llm_provider or "google",
            status="completed",
            error_message=error_msg
        )
        
    except Exception as e:
        # Handle failures before streaming starts gracefully by updating the request
        await generation_repo.update_generation_request(
            session=session,
            request_id=request_id,
            status="failed",
            error_message=str(e)
        )
        yield f"3:{json.dumps(str(e))}\n"
