"""add_rate_limiting

Revision ID: 14748d0beb81
Revises: 0316c2b5c008
Create Date: 2026-07-14 10:18:44.622903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14748d0beb81'
down_revision: Union[str, Sequence[str], None] = '0316c2b5c008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('document_chunks_embedding_idx'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_generation_request_client_id_created_at_desc'), table_name='generation_requests')
    op.create_index('ix_generation_request_client_id_created_at_desc', 'generation_requests', ['client_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.add_column('tenants', sa.Column('rate_limit_per_minute', sa.Integer(), server_default=sa.text('60'), nullable=False))
    op.add_column('tenants', sa.Column('request_count_this_minute', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('tenants', sa.Column('rate_limit_window_start', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('tenants_api_key_hash_key'), 'tenants', type_='unique')
    op.drop_column('tenants', 'api_key_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('tenants_api_key_hash_key'), 'tenants', ['api_key_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'rate_limit_window_start')
    op.drop_column('tenants', 'request_count_this_minute')
    op.drop_column('tenants', 'rate_limit_per_minute')
    op.drop_index('ix_generation_request_client_id_created_at_desc', table_name='generation_requests', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_generation_request_client_id_created_at_desc'), 'generation_requests', ['client_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('document_chunks_embedding_idx'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
