"""add byok usage reset

Revision ID: 34409417c419
Revises: 22ba3ea77974
Create Date: 2026-07-15 16:11:16.600912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34409417c419'
down_revision: Union[str, Sequence[str], None] = '22ba3ea77974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('usage_reset_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_generation_request_client_id_created_at_desc'), table_name='generation_requests')
    op.create_index('ix_generation_request_client_id_created_at_desc', 'generation_requests', ['client_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generation_request_client_id_created_at_desc', table_name='generation_requests', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_generation_request_client_id_created_at_desc'), 'generation_requests', ['client_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('clients', 'usage_reset_at')
    # ### end Alembic commands ###
