"""add_analytics

Revision ID: fefab08754ee
Revises: 34409417c419
Create Date: 2026-07-17 20:35:45.734070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fefab08754ee'
down_revision: Union[str, Sequence[str], None] = '34409417c419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('generation_request_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['generation_request_id'], ['generation_requests.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_event_client_id_created_at', 'analytics_events', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_analytics_event_tenant_id_created_at', 'analytics_events', ['tenant_id', 'created_at'], unique=False)
    op.add_column('generation_requests', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('generation_requests', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('generation_requests', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('generation_requests', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_generation_request_client_id_created_at_desc'), table_name='generation_requests')
    op.create_index('ix_generation_request_client_id_created_at_desc', 'generation_requests', ['client_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generation_request_client_id_created_at_desc', table_name='generation_requests', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_generation_request_client_id_created_at_desc'), 'generation_requests', ['client_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('generation_requests', 'duration_ms')
    op.drop_column('generation_requests', 'total_tokens')
    op.drop_column('generation_requests', 'completion_tokens')
    op.drop_column('generation_requests', 'prompt_tokens')
    op.drop_index('ix_analytics_event_tenant_id_created_at', table_name='analytics_events')
    op.drop_index('ix_analytics_event_client_id_created_at', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
